// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWuChP47eHiuGgvf_DD9QPQ9KruoMpn_E',
    appId: '1:362736843506:web:1bd7d6dd56d4748f6dae6b',
    messagingSenderId: '362736843506',
    projectId: 'benneteddar-6e01f',
    authDomain: 'benneteddar-6e01f.firebaseapp.com',
    storageBucket: 'benneteddar-6e01f.appspot.com',
    measurementId: 'G-8MHQ6VWMVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAedYuLEcL0vLiCsCyKBQqF0c-vDKxMyIk',
    appId: '1:362736843506:android:fe8af299bb76e9666dae6b',
    messagingSenderId: '362736843506',
    projectId: 'benneteddar-6e01f',
    storageBucket: 'benneteddar-6e01f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKiHnuJJnbI56BdcuwdALBtZcz3I4USds',
    appId: '1:362736843506:ios:c741fedeb5f892f96dae6b',
    messagingSenderId: '362736843506',
    projectId: 'benneteddar-6e01f',
    storageBucket: 'benneteddar-6e01f.appspot.com',
    iosBundleId: 'com.example.bennetEddarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKiHnuJJnbI56BdcuwdALBtZcz3I4USds',
    appId: '1:362736843506:ios:09ca21f95f8543266dae6b',
    messagingSenderId: '362736843506',
    projectId: 'benneteddar-6e01f',
    storageBucket: 'benneteddar-6e01f.appspot.com',
    iosBundleId: 'com.example.bennetEddarApp.RunnerTests',
  );
}
